blank_issues_enabled: false
contact_links:
  - name: Confidential Issue Reporting Form
    url: https://forms.gle/nfhSWydqweesh4iq7
    about: Report security concerns or other issues that should not be visible to the public
